modLoader="javafml" #mandatory
loaderVersion="[47,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
issueTrackerURL="https://github.com/mattieof/YouveGotMail/issues"

[[mods]] #mandatory
   modId="youvegotmail" #mandatory
   version="${version}" #mandatory
   displayName="You've Got Mail"
   displayURL="https://www.curseforge.com/minecraft/mc-mods/youve-got-mail"
   logoFile="assets/youvegotmail/icon.png" #optional
   description='''
   Adds mail notifications to Mighty Mail
   '''

[[dependencies.youvegotmail]]
   modId="forge"
   mandatory=true
   versionRange="[47,)"
   ordering="NONE"
   side="BOTH"

[[dependencies.youvegotmail]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.20.1,1.21)"
   ordering="NONE"
   side="BOTH"

[[dependencies.youvegotmail]]
   modId="mighty_mail"
   mandatory=true
   versionRange="[1.0.14,1.1)"
   ordering="NONE"
   side="BOTH"
